a=int(input("A:"))
b=int(input("B:"))
operation=input("sub\add\mul\div:")
if(operation=="add"):
    print(a+b)
elif(operation=="sub"):
    print(a-b)
elif(operation=="div"):
    print(a/b)
elif(operation=="mul"):
    print(a*b)
else:
    print("INVALID")
